codecov:
  strict_yaml_branch: main

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
        informational: true
    patch: off

comment:
  after_n_builds: 1
  require_changes: true
